# -*- coding: utf-8 -*-
"""
Created on Wed Oct 31 13:50:31 2018

@author: aelshaha
"""

class EVENTS():
    
    YEAR_ADDING     = "YEAR_ADDING_"
    YEAR_ADDED      = "YEAR_ADDED_"
    YEAR_REMOVING   = "YEAR_REMOVING_"
    YEAR_REMOVED    = "YEAR_REMOVED_"
    
    SITE_ADDING     = "SITE_ADDING_"
    SITE_ADDED      = "SITE_ADDED_"
    SITE_REMOVING   = "SITE_REMOVING_"
    SITE_REMOVED    = "SITE_REMOVED_"
    
    RES_SELECTED    = "RES_SELECTED_"
    
    COMMODITY_ADDING     = "COMMODITY_ADDING_"
    COMMODITY_ADDED      = "COMMODITY_ADDED_"
    COMMODITY_EDITING    = "COMMODITY_EDITING_"
    COMMODITY_EDITED     = "COMMODITY_EDITED_"
    COMMODITY_SAVE       = "COMMODITY_SAVE_"
    COMMODITY_REMOVING   = "COMMODITY_REMOVING_"
    COMMODITY_REMOVED    = "COMMODITY_REMOVED_"
    COMMODITY_SELECTED   = "COMMODITY_SELECTED_"
    COMMODITY_DESELECTED = "COMMODITY_DESELECTED_"
    
    PROCESS_ADDING     = "PROCESS_ADDING_"
    PROCESS_ADDED      = "PROCESS_ADDED_"
    PROCESS_EDITING    = "PROCESS_EDITING_"
    PROCESS_EDITED     = "PROCESS_EDITED_"
    PROCESS_SAVE       = "PROCESS_SAVE_"
    PROCESS_REMOVING   = "PROCESS_REMOVING_"
    PROCESS_REMOVED    = "PROCESS_REMOVED_"
    PROCESS_SELECTED   = "PROCESS_SELECTED_"
    PROCESS_DESELECTED = "PROCESS_DESELECTED_"
        
    CONNECTION_EDITING = "CONNECTION_EDITING_"
    
    STORAGE_ADDING     = "STORAGE_ADDING_"
    STORAGE_ADDED      = "STORAGE_ADDED_"
    STORAGE_EDITING    = "STORAGE_EDITING_"
    STORAGE_EDITED     = "STORAGE_EDITED_"
    STORAGE_SAVE       = "STORAGE_SAVE_"
    
    ITEM_DOUBLE_CLICK  = "ITEM_DOUBLE_CLICK_"
    ITEM_MOVED         = "ITEM_MOVED_"
    SAVE_CONFIG        = "SAVE_CONFIG_"
    LOAD_CONFIG        = "LOAD_CONFIG_"