# -*- coding: utf-8 -*-
"""
Created on Wed Oct 31 13:50:31 2018

@author: aelshaha
"""

class EVENTS():
    
    YEAR_ADDING     = "YEAR_ADDING"
    YEAR_ADDED      = "YEAR_ADDED"
    YEAR_REMOVING   = "YEAR_REMOVING"
    YEAR_REMOVED    = "YEAR_REMOVED"
    
    SITE_ADDING     = "SITE_ADDING"
    SITE_ADDED      = "SITE_ADDED"
    SITE_REMOVING   = "SITE_REMOVING"
    SITE_REMOVED    = "SITE_REMOVED"
    
    COMMODITY_ADDING     = "COMMODITY_ADDING"
    COMMODITY_EDITING    = "COMMODITY_EDITING"
    COMMODITY_ADDED      = "COMMODITY_ADDED"
    COMMODITY_REMOVING   = "COMMODITY_REMOVING"
    COMMODITY_REMOVED    = "COMMODITY_REMOVED"
    
    PROCESS_ADDING     = "PROCESS_ADDING"
    PROCESS_EDITING    = "PROCESS_EDITING"
    PROCESS_ADDED      = "PROCESS_ADDED"
    PROCESS_REMOVING   = "PROCESS_REMOVING"
    PROCESS_REMOVED    = "PROCESS_REMOVED"
    
    SHAPE_DOUBLE_CLICK  = "SHAPE_DOUBLE_CLICK"
    