# -*- coding: utf-8 -*-
"""
Created on Wed Oct 31 13:50:31 2018

@author: aelshaha
"""

class EVENTS():
    
    YEAR_ADDING     = "YEAR_ADDING"
    YEAR_ADDED      = "YEAR_ADDED"
    YEAR_REMOVING   = "YEAR_REMOVING"
    YEAR_REMOVED    = "YEAR_REMOVED"
    
    SITE_ADDING     = "SITE_ADDING"
    SITE_ADDED      = "SITE_ADDED"
    SITE_REMOVING   = "SITE_REMOVING"
    SITE_REMOVED    = "SITE_REMOVED"
    
    RES_SELECTED    = "RES_SELECTED"
    
    COMMODITY_ADDING     = "COMMODITY_ADDING"
    COMMODITY_ADDED      = "COMMODITY_ADDED"
    COMMODITY_EDITING    = "COMMODITY_EDITING"
    COMMODITY_EDITED     = "COMMODITY_EDITED"
    COMMODITY_SAVE       = "COMMODITY_SAVE"    
    COMMODITY_REMOVING   = "COMMODITY_REMOVING"
    COMMODITY_REMOVED    = "COMMODITY_REMOVED"
    COMMODITY_SELECTED   = "COMMODITY_SELECTED"
    COMMODITY_DESELECTED = "COMMODITY_DESELECTED"
    
    PROCESS_ADDING     = "PROCESS_ADDING"
    PROCESS_ADDED      = "PROCESS_ADDED"
    PROCESS_EDITING    = "PROCESS_EDITING"
    PROCESS_EDITED     = "PROCESS_EDITED"
    PROCESS_SAVE       = "PROCESS_SAVE"    
    PROCESS_REMOVING   = "PROCESS_REMOVING"
    PROCESS_REMOVED    = "PROCESS_REMOVED"
    PROCESS_SELECTED   = "PROCESS_SELECTED"
    PROCESS_DESELECTED = "PROCESS_DESELECTED"
        
    CONNECTION_EDITING = "CONNECTION_EDITING"
    
    ITEM_DOUBLE_CLICK  = "ITEM_DOUBLE_CLICK"
    